### ISSUE TITLE
请教blog

### ISSUE THREAD

**Issue by xiaobaisky** [vwin/vwin.github.io#12]
你好，能请教一下怎么建立blog吗？

**Comment by vwin** [comment]
可以参考  
https://linghucong.js.org/2016/04/15/2016-04-15-hexo-github-pages-blog/


------------------ 原始邮件 ------------------
发件人: haisky <notifications@github.com>
发送时间: 2019年6月9日 09:34
收件人: vwin/vwin.github.io <vwin.github.io@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[vwin/vwin.github.io] 请教blog (#12)




你好，能请教一下怎么建立blog吗？
